### ISSUE TITLE
Why do we need this part?

### ISSUE THREAD

**Issue by steveguang** [sadimanna/simclr_pytorch#1]
Hi, @sadimanna , in the PreModel, why do we need below? Thanks!
 self.pretrained.conv1 = nn.Conv2d(3, 64, kernel_size=(3, 3), stride=(1, 1), bias=False)

**Comment by sadimanna** [comment]
This is mainly done to avoid errors due to negative dimensions resulting due to 32X32 input size from CIFAR-10. This has been suggested in the paper itself (in the Appendix). If your use 64X64 or 96X96 you may not need that part.
