### ISSUE TITLE
Test results of your experiment.

### ISSUE THREAD

**Issue by pvmilk** [sadimanna/simclr_pytorch#2]
I cannot find the test result of you experiment report anywhere both in the [blog](https://medium.com/the-owl/simclr-in-pytorch-5f290cb11dd7) or in the github notebook. 

P.S. One assumption is that the value must be very high since the network is pre-trained with ImageNet isn't it?

**Comment by sadimanna** [comment]
@pvmilk Yes, you are right. I think I have mentioned the test results in the blog towards the end. It should be 85-90%.
